version: "3.7"

services:
  system-manager:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code/templates:/opt/nuvlabox/templates
      - ./code/static:/opt/nuvlabox/static
      - ./code/test/.nuvlabox-status:/srv/nuvlabox/shared/.nuvlabox-status
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    ports:
      - 127.0.0.1:3637:3636


