version: "3.7"

services:
  system-manager:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code/templates/dashboard.html:/opt/nuvlabox/templates/dashboard.html
      - ./code/static:/opt/nuvlabox/static
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    ports:
      - 127.0.0.1:3636:3636
      - 3637:3637


